# Generated by Django 4.1.1 on 2022-12-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_category_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='User')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone_number', models.IntegerField(max_length=15, verbose_name='Nömrə')),
                ('position', models.CharField(max_length=20, verbose_name='Sahə')),
                ('about', models.TextField(verbose_name='Haqqında')),
            ],
        ),
    ]
